### ISSUE TITLE
Gặp vấn đề về cách chạy app

### ISSUE THREAD

**Issue by HanKienjd** [nguyendinhkien/CardId#2]
Em là khoá sau , clone project của anh về nhưng đang không thể connect được với Thẻ ảo. Mong anh giúp đỡ

**Comment by nguyendinhkien** [comment]
> Em là khoá sau , clone project của anh về nhưng đang không thể connect được với Thẻ ảo. Mong anh giúp đỡ

Chào bạn, đầu tiên bạn cần cài 2 IDE:
- Netbeans IDE: dùng để chạy app CardID
- JCIDE: Chạy máy ảo java card (project save_image)
Lưu ý khi Run project trên JCIDE cần bật Enable PCSC Interface, bây giờ trên app bạn có thể refresh và chọn thẻ java card ảo để connect
Chi tiết bạn có thể tìm hiểu thêm ở [](https://www.studocu.com/vn/document/hoc-vien-ky-thuat-quan-su/cong-nghe-thong-tin/huong-dan-connect-smartcard-su-dung-java/27185167)

**Comment by nguyendinhkien** [comment]
> Em là khoá sau , clone project của anh về nhưng đang không thể connect được với Thẻ ảo. Mong anh giúp đỡ

Chào bạn, đầu tiên bạn cần cài 2 IDE:

Netbeans IDE: dùng để chạy app CardID/DichVuCong
JCIDE: Chạy máy ảo java card (project save_image)
Lưu ý khi Run project trên JCIDE cần bật Enable PCSC Interface(Tool>IDE Options>Run/Debug)
Bây giờ trên app bạn có thể refresh và chọn thẻ java card ảo để connect
