### ISSUE TITLE
Lỗi không select được card đã active 9000 

### ISSUE THREAD

**Issue by HanKienjd** [nguyendinhkien/CardId#3]
![image](https://user-images.githubusercontent.com/50418911/170319365-63f9d57b-d02a-4c11-a9d2-77cb7f556571.png)

**Comment by nguyendinhkien** [comment]
Bạn xem có xoá nhầm dòng này không nhé, biến javaCard chưa được khởi tạo dẫn đến Null
`javaCard = new JavaSmartcard();`
![image](https://user-images.githubusercontent.com/37918536/170324062-202b7a28-a759-4856-a8a5-97068a1948e2.png)
