### ISSUE TITLE
Hỏi về mã pin connect card

### ISSUE THREAD

**Issue by HanKienjd** [nguyendinhkien/CardId#4]
Khi login thì em đang xuất hiện lỗi này
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Uncompilable code - ')' expected
![image](https://user-images.githubusercontent.com/50418911/171696434-8703ae98-25a8-4ea1-97fd-c44e6989cdbd.png)

**Comment by nguyendinhkien** [comment]
mã pin được đăng ký ở app CardID nhé.

**Comment by HanKienjd** [comment]
> mã pin được đăng ký ở app CardID nhé.

Em mò được đến đó rồi ạ, như ảnh em gửi thì khi em nhập mã Pin trả về lỗi kia, em không xác định được nguyên nhân do đâu

**Comment by LeHocHoangAnh** [comment]
em đăng ký xong rồi login thì phần hiển thị ảnh nó chỉ load được 1 chút anh ạ ,với chỉ chọn được ảnh đuổi jpg thôi à anh có cách nào khắc phục không ạ 
![image](https://user-images.githubusercontent.com/94533277/172058557-01e57c27-ad6e-4fcd-ab6b-0be02023153f.png)
với phần select card này thì chọn cái trên hay dưới và tại sao lại tạo ra 2 cái ạ 
![image](https://user-images.githubusercontent.com/94533277/172058609-da2836e0-82fa-4719-a6f9-e520d7241295.png)
mong anh giúp ạ em cảm ơn ạ !

**Comment by nguyendinhkien** [comment]
> > mã pin được đăng ký ở app CardID nhé.
> 
> Em mò được đến đó rồi ạ, như ảnh em gửi thì khi em nhập mã Pin trả về lỗi kia, em không xác định được nguyên nhân do đâu

Code thiếu  dấu ) hay sao ấy mà IDE n vẫn cho chạy, em dùng intellij chạy là ra chỗ code sai

**Comment by nguyendinhkien** [comment]
> em đăng ký xong rồi login thì phần hiển thị ảnh nó chỉ load được 1 chút anh ạ ,với chỉ chọn được ảnh đuổi jpg thôi à anh có cách nào khắc phục không ạ ![image](https://user-images.githubusercontent.com/94533277/172058557-01e57c27-ad6e-4fcd-ab6b-0be02023153f.png) 

Do chuyển ảnh sang Base64 để lưu nhưng chuỗi string có giới hạn nên phải giới hạn kích thước ảnh, em có thể nối nhiều chuỗi string để lưu ảnh nhưng nhanh hơn là resize lại ảnh, khoảng 25KB

**Comment by nguyendinhkien** [comment]
>với phần select card này thì chọn cái trên hay dưới và tại sao lại tạo ra 2 cái ạ ![image](https://user-images.githubusercontent.com/94533277/172058609-da2836e0-82fa-4719-a6f9-e520d7241295.png) mong anh giúp ạ em cảm ơn ạ !

máy ảo n tạo ra 2 loại thẻ (contact và contactless), chọn 1 trong 2
